require "active_support/core_ext/integer/time"
require_relative "../../lib/bullet_safelists"

# Required explicitly (not autoloaded): environment config runs before Zeitwerk
# autoloading is active — same pattern as config/initializers/markdowndocs.rb.
require_relative "../../lib/codespaces"

Rails.application.configure do
  config.enable_reloading = true
  config.eager_load = false
  config.consider_all_requests_local = true
  config.server_timing = true

  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  config.cache_store = :memory_store
  config.active_storage.service = :local

  # Active Record Encryption keys for the development database (#902).
  # Literal on purpose: the template ships no credentials, and a fresh clone
  # must run without secrets. Rails applies these OVER credentials — a fork
  # that adds development credentials later must delete these lines for them
  # to win. A database written before these keys existed is not readable:
  # `bin/rails db:reset`.
  config.active_record.encryption.primary_key = "JfGPNf7LqnoT4u0efBUt5hNwZzUdjLCq"
  config.active_record.encryption.deterministic_key = "31pHrP5HHKRr56fRPcyI8mc3DqVxAzh9"
  config.active_record.encryption.key_derivation_salt = "0zM3DPgftgScUasAmjXcJLtlcEndyoUE"

  config.action_mailer.raise_delivery_errors = false
  config.action_mailer.perform_caching = false
  config.action_mailer.delivery_method = :letter_opener_web

  # Set localhost to be used by links generated in mailer templates.
  # Port follows the PORT env var so letter_opener links match the running server
  # (e.g. PORT=3001 bin/dev → links use 3001). bin/dev exports PORT before foreman starts;
  # puma.rb reads the same env var, so both are always in sync.
  config.action_mailer.default_url_options = { host: "localhost", port: ENV.fetch("PORT", 3000).to_i }

  # GitHub Codespaces: the browser reaches the app through a forwarded HTTPS
  # proxy at <codespace>-<port>.app.github.dev, not localhost. Allow that host
  # past DNS-rebinding protection and point mailer links (magic-link sign-in) at
  # the forwarded URL so they resolve in the browser. No-op outside Codespaces.
  if Codespaces.active?
    config.hosts << ".#{Codespaces.forwarding_domain}"

    config.action_mailer.default_url_options = {
      host: Codespaces.forwarded_host(port: ENV.fetch("PORT", 3000)),
      protocol: "https"
    }

    # The forwarded Host never matches the browser's Origin, so the Origin check would refuse every form;
    # Sec-Fetch-Site still guards writes. See /docs/developer/codespaces.
    config.action_controller.forgery_protection_origin_check = false
  end

  config.active_support.deprecation = :log
  config.active_record.migration_error = :page_load
  config.active_record.verbose_query_logs = true
  config.active_record.query_log_tags_enabled = true
  config.active_job.verbose_enqueue_logs = true

  # Route Solid Queue's models to the dedicated queue database
  # (mirrors production so deliver_later jobs land where bin/jobs polls).
  config.solid_queue.connects_to = { database: { writing: :queue } }

  config.action_dispatch.verbose_redirect_logs = true
  config.assets.quiet = true

  # Raises error for missing translations. Left off deliberately: a missing key
  # renders inline here, which is the more useful signal while a page is still
  # being built. Test raises, and the Lefthook pre-push hook runs the suite, so
  # it cannot reach a PR.
  # config.i18n.raise_on_missing_translations = true

  # Match production's fallback chain. Without this, `config.i18n.fallbacks`
  # stays an empty OrderedOptions, `validate_fallbacks` returns false, and the
  # Fallbacks module is never included — leaving I18n.fallbacks with no :en
  # terminator and development the least production-like of the three envs.
  config.i18n.fallbacks = true

  config.action_view.annotate_rendered_view_with_filenames = true
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # NOTE: this hook does not fire for `modelrails_ui:add` (observed 2026-08-21) —
  # after regenerating vendored UI files, run `bin/rubocop -A` on them; that is
  # the proven convergence step (regenerate + -A == byte-identical, zero diff).
  config.generators.apply_rubocop_autocorrect_after_generate!

  config.hotwire.spark.html_paths += %w[ app/components ]
  config.hotwire.spark.css_paths = %w[ app/assets/builds ]

  config.after_initialize do
    Bullet.enable = true
    Bullet.alert = true
    Bullet.bullet_logger = true
    Bullet.console = true
    Bullet.rails_logger = true
    Bullet.add_footer = true

    BulletSafelists.apply
  end
end
